name: main

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            configurePreset: msbuild-x64
            buildPreset: msbuild-x64-release
            name: ezQuake-windows-x64
            artifact: "ezquake.exe"
          - os: ubuntu-latest
            configurePreset: dynamic
            buildPreset: dynamic-release
            name: ezQuake-linux-x86_64
            artifact: "ezQuake-x86_64.AppImage"
            cflags: "-march=nehalem"
            packages: ["build-essential", "ca-certificates", "cmake", "curl", "file", "git", "libcurl4-openssl-dev", "libexpat1-dev", "libfreetype-dev", "libfuse3-dev", "libjansson-dev", "libjpeg-dev", "libminizip-dev", "libpcre2-dev", "libpng-dev", "libsdl2-2.0-0", "libsdl2-dev", "libsndfile1-dev", "libspeex-dev", "libspeexdsp-dev", "ninja-build", "unzip"]
            container:
              image: debian:testing
              options: --privileged

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - name: Prepare Linux environment
      run: |
        apt-get -qq update && apt-get -qq install --no-install-recommends ${{ join(matrix.packages, ' ') }}
        git config --global --add safe.directory $PWD
      if: matrix.os == 'ubuntu-latest'

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Initialize submodules
      run: |
        git submodule add https://github.com/Microsoft/vcpkg vcpkg || true
        git submodule add https://github.com/QW-Group/qwprot src/qwprot || true
        git submodule update --init --recursive

    - name: Fetch upstream tags for version metadata
      run: |
        git remote add upstream https://github.com/QW-Group/ezquake-source.git || true
        git fetch --tags --no-recurse-submodules upstream

    - name: Set library build type to release
      shell: bash
      run: |
        for x in cmake/triplets/* vcpkg/triplets/* vcpkg/triplets/community/*; do
          if [[ -f $x ]]; then
            echo 'set(VCPKG_BUILD_TYPE release)' >> $x
          fi
        done
      if: matrix.os != 'ubuntu-late
